name: Article Spell Check
on: [pull_request]
jobs:
  Spell-Check:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install -g markdown-spellcheck
    - run: |
        FILES=$(git diff-tree --no-commit-id --name-only -r $(git rev-parse --verify HEAD))
        for file in $FILES ; do 
          markdown-spellcheck $file '!**/node_modules/**/*.md'
        Sdone