name: Article Spell Check
on: [pull_request]
jobs:
  Spell-Check:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jitterbit/get-changed-files@v1
      id: files
    - run: npm install -g markdown-spellcheck
    - run: |
        for file in ${{ steps.files.outputs.all }}; do 
          if [[ "${file}" == "*.md" ]]; then
            npm markdown-spellcheck ${file} '!**/node_modules/**/*.md'; 
          fi
        done
      name: Spell Check Changed Files